on: push

name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v6

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ftp-lequaiantique.alwaysdata.net
          username: lequaiantique
          password: ${{ secrets.ftp_password }}
          protocol: ftps-legacy
          port: 990
          server-dir: /www/
          timeout: 120000
          log-level: verbose
          exclude: |
            **/.git*
            **/node_modules/bootstrap/scss/**
            **/node_modules/bootstrap/js/**
            **/node_modules/bootstrap-icons/icons/**
